server_port: 8080
api_prefix: v1
database:
  host: localhost
  port: 27018
  username: admin
  password: Abc12345
  db_name: musictrack_db

file_path:
  thumbnail: data/thumbnails
  music_track: data/songs