services:
  mongo_db:
    container_name: musictrack_db
    image: mongo:5.0.5
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: musictrack_db
      MONGO_INITDB_USERNAME: admin
      MONGO_INITDB_PASSWORD: Abc12345
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    container_name: golang_api
    build:
      context: ./../
      dockerfile: Dockerfile